#!/bin/sh

# we must be root
[ $(whoami) = "root" ] || { echo "E: You must be root" && exit 1; }

# we must have few tools
SGDISK=$(which sgdisk) || { echo "E: You must have sgdisk" && exit 1; }
PARTED=$(which parted) || { echo "E: You must have parted" && exit 1; }
PARTPROBE=$(which partprobe) || { echo "E: You must have partprobe" && exit 1; }
RESIZE2FS=$(which resize2fs) || { echo "E: You must have resize2fs" && exit 1; }

# find root device
ROOT_DEVICE=$(findmnt --noheadings --output=SOURCE / | cut -d'[' -f1)
# prune root device (for example UUID)
ROOT_DEVICE=$(realpath ${ROOT_DEVICE})
# get the partition number
PARTITION=$(lsblk --noheadings --output=MAJ:MIN ${ROOT_DEVICE} | cut -d':' -f2)
# find the block device
DEVICE=$(lsblk --noheadings --output=MAJ:MIN ${ROOT_DEVICE} | cut -d':' -f1)
DEVICE=$(lsblk --noheadings --output=NAME,MAJ:MIN | grep "${DEVICE}:0"  | cut -d' ' -f1)
DEVICE="/dev/${DEVICE}"

${SGDISK} -e ${DEVICE}
${PARTPROBE}
${PARTED} ${DEVICE} resizepart ${PARTITION} Yes 100%
${PARTPROBE}
${RESIZE2FS} "${ROOT_DEVICE}"
