70-96boards-common.rules    lib/udev/rules.d/
96boards-sensors.sh         etc/profile.d/
# for 410c
#extlinux/*                  usr/share/96boards-tools/extlinux
flash-hikey                 usr/share/96boards-tools/
grub-install-hikey          usr/sbin
grub/*                      usr/share/96boards-tools/grub
resize-helper               usr/sbin
resize-helper.service       lib/systemd/system
zz-copy-devicetree          etc/kernel/postinst.d
zz-copy-devicetree          etc/kernel/postrm.d
